export const FIELD = {
  id: "id",
  accountId: "accountId",
  fromAccountId: "fromAccountId",
  toAccountId: "toAccountId",
  accountIds: "accountIds",
  categoryId: "categoryId",
  parentId: "parentId",
  transactionId: "transactionId",
  outflowId: "outflowId",
  inflowId: "inflowId",
  occurrenceId: "occurrenceId",
  recurringItemId: "recurringItemId",
  name: "name",
  members: "members",
  type: "type",
  kind: "kind",
  flow: "flow",
  amount: "amount",
  date: "date",
  notes: "notes",
  start: "start",
  end: "end",
  minimum: "minimum",
  percent: "percent",
  cadence: "cadence",
  classification: "classification",
  color: "color",
  nature: "nature",
  description: "description",
  decision: "decision",
  rememberForAll: "rememberForAll",
  nextStatus: "nextStatus",
  creditLimitCents: "creditLimitCents",
  annualRatePct: "annualRatePct",
  minimumPayment: "minimumPayment",
  paymentDueDay: "paymentDueDay",
  targetAmount: "targetAmount",
  targetDate: "targetDate",
  estimatedAmount: "estimatedAmount",
  dayOfMonth: "dayOfMonth",
} as const;

export type FieldName = (typeof FIELD)[keyof typeof FIELD];

export const FORM_VALUE = {
  checkboxOn: "on",
} as const;
